# Generated by Django 5.1.5 on 2025-01-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='url_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('twitch', 'Twitch'), ('pinterest', 'Pinterest'), ('reddit', 'Reddit'), ('snapchat', 'Snapchat'), ('spotify', 'Spotify'), ('tumblr', 'Tumblr'), ('website', 'Website'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
