# Generated by Django 5.1.5 on 2025-01-20 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_link_clicks_count_user_views_count_pageview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_marca', models.CharField(default='Minha Marca', max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='logotipos/')),
                ('tema', models.CharField(default='padrao', max_length=50)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('total_visualizacoes', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='link',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='profiles.brand'),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='profiles.brand'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
