# Generated by Django 5.1.5 on 2025-01-20 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_brand_alter_link_user_alter_pageview_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='user',
            new_name='brand',
        ),
    ]
