# Generated by Django 5.1.5 on 2025-01-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_rename_user_link_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageview',
            old_name='user',
            new_name='brand',
        ),
    ]
