# Generated by Django 5.1.5 on 2025-01-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_rename_user_pageview_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
